void setupLEDS();
void runningMode();
void stationaryMode();
void shiftOut(int, int, byte);
void blinkGreenTwice();
void greenStationary();
void redStationary();
void greenRunning();
void redRunning();
void connectMode();
