void setupLEDS();
void runningMode();
void stationaryMode();
void shiftOut(int, int, byte);
void blinkAll_2Bytes(int , int);
void greenStationary();
void redStationary();
void greenRunning();
void redRunning();
void connectMode();
